In [1]:
import pandas as pd

In [24]:
df = pd.read_csv('df_houses_new.csv')

In [3]:
df.head()

,Parking,Flooring,Laundry,Dishwasher,Stainless_Appliances,Cable,Internet,Outdoor_Spaces,AC,Pool,...,City,rental_type,Price,Unit_Type,Bedrooms,city_clean,state_clean,latitude,longitude,location
0,not,other,not,not,not,not,not,No Outdoor Space,not,not,...,Washington,Monthly,940.0,studio,0,washington,dc,38.912217,-77.017691,"washington,dc"
1,not,other,not,not,not,not,not,No Outdoor Space,not,not,...,Evansville,Monthly,425.0,studio,0,evansville,in,37.974600,-87.567400,"evansville,in"
2,not,other,not,not,not,not,not,No Outdoor Space,not,not,...,Evansville,Monthly,445.0,1 bedroom,1,evansville,in,37.974600,-87.567400,"evansville,in"
3,not,other,not,not,not,not,not,Combined,not,not,...,Arlington,Monthly,1390.0,studio,0,arlington,va,38.887103,-77.093197,"arlington,va"
4,not,other,not,not,not,not,not,No Outdoor Space,not,not,...,Seattle,Monthly,925.0,studio,0,seattle,wa,47.611435,-122.330456,"seattle,wa"

In [4]:
df.drop(['location', 'City', 'State'], axis = 1)

,Parking,Flooring,Laundry,Dishwasher,Stainless_Appliances,Cable,Internet,Outdoor_Spaces,AC,Pool,Fitness_Facilities,rental_type,Price,Unit_Type,Bedrooms,city_clean,state_clean,latitude,longitude
0,not,other,not,not,not,not,not,No Outdoor Space,not,not,not,Monthly,940.0,studio,0,washington,dc,38.912217,-77.017691
1,not,other,not,not,not,not,not,No Outdoor Space,not,not,not,Monthly,425.0,studio,0,evansville,in,37.974600,-87.567400
2,not,other,not,not,not,not,not,No Outdoor Space,not,not,not,Monthly,445.0,1 bedroom,1,evansville,in,37.974600,-87.567400
3,not,other,not,not,not,not,not,Combined,not,not,not,Monthly,1390.0,studio,0,arlington,va,38.887103,-77.093197
4,not,other,not,not,not,not,not,No Outdoor Space,not,not,not,Monthly,925.0,studio,0,seattle,wa,47.611435,-122.330456
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12371,not,other,not,not,not,not,not,No Outdoor Space,not,not,not,Monthly,3980.0,5 bedroom,5,arvada,co,39.803900,-105.085900
12372,not,other,not,not,not,not,not,No Outdoor Space,not,not,not,Monthly,19500.0,4 bedroom,4,los angeles,ca,33.973093,-118.247896
12373,not,other,not,not,not,not,not,No Outdoor Space,not,not,not,Monthly,4500.0,4 bedroom,4,eden prairie,mn,44.857426,-93.437573
12374,not,other,not,not,not,not,not,No Outdoor Space,not,not,not,Monthly,6900.0,5 bedroom,5,lutz,fl,28.143000,-82.475200
12375,not,other,not,not,not,not,not,No Outdoor Space,not,not,not,Monthly,6000.0,5 bedroom,5,edina,mn,44.889703,-93.350122

In [29]:
df['Fitness_Facilities'].value_counts()

Fitness_Facilities
not          8889
available    3470
Name: count, dtype: int64

In [25]:
recode_map = {
    "not": False,
    "provided": True
}

# Apply the map to the 'Internet' column.
# The original values are replaced with the corresponding values from the map.
df['Parking'] = df['Parking'].map(recode_map)
df['Laundry'] = df['Laundry'].map(recode_map)
df['Dishwasher'] = df['Dishwasher'].map(recode_map)
df['Stainless_Appliances'] = df['Stainless_Appliances'].map(recode_map)
df['AC'] = df['AC'].map(recode_map)
df['Pool'] = df['Pool'].map(recode_map)

In [26]:
recode_map = {
    "not": False,
    "included": True
}

# Apply the map to the 'Internet' column.
# The original values are replaced with the corresponding values from the map.
df['Internet'] = df['Internet'].map(recode_map)
df['Cable'] = df['Cable'].map(recode_map)

In [27]:
recode_map = {
    "No Outdoor Space": False,
    ("Combined","Balcony","Patio", "Deck")  : True
}

# Apply the map to the 'Internet' column.
# The original values are replaced with the corresponding values from the map.
df['Outdoor_Spaces'] = df['Outdoor_Spaces'].map(recode_map)

In [28]:
df_new = df.drop(['location', 'City', 'State', 'Flooring'], axis = 1)
df_new.head()

,Parking,Laundry,Dishwasher,Stainless_Appliances,Cable,Internet,Outdoor_Spaces,AC,Pool,Fitness_Facilities,rental_type,Price,Unit_Type,Bedrooms,city_clean,state_clean,latitude,longitude
0,False,False,False,False,False,False,False,False,False,not,Monthly,940.0,studio,0,washington,dc,38.912217,-77.017691
1,False,False,False,False,False,False,False,False,False,not,Monthly,425.0,studio,0,evansville,in,37.974600,-87.567400
2,False,False,False,False,False,False,False,False,False,not,Monthly,445.0,1 bedroom,1,evansville,in,37.974600,-87.567400
3,False,False,False,False,False,False,NaN,False,False,not,Monthly,1390.0,studio,0,arlington,va,38.887103,-77.093197
4,False,False,False,False,False,False,False,False,False,not,Monthly,925.0,studio,0,seattle,wa,47.611435,-122.330456

In [30]:
recode_map = {
    "not": False,
    "available": True
}

# Apply the map to the 'Internet' column.
# The original values are replaced with the corresponding values from the map.
df_new['Fitness_Facilities'] = df_new['Fitness_Facilities'].map(recode_map)

In [31]:
df_new.head()

,Parking,Laundry,Dishwasher,Stainless_Appliances,Cable,Internet,Outdoor_Spaces,AC,Pool,Fitness_Facilities,rental_type,Price,Unit_Type,Bedrooms,city_clean,state_clean,latitude,longitude
0,False,False,False,False,False,False,False,False,False,False,Monthly,940.0,studio,0,washington,dc,38.912217,-77.017691
1,False,False,False,False,False,False,False,False,False,False,Monthly,425.0,studio,0,evansville,in,37.974600,-87.567400
2,False,False,False,False,False,False,False,False,False,False,Monthly,445.0,1 bedroom,1,evansville,in,37.974600,-87.567400
3,False,False,False,False,False,False,NaN,False,False,False,Monthly,1390.0,studio,0,arlington,va,38.887103,-77.093197
4,False,False,False,False,False,False,False,False,False,False,Monthly,925.0,studio,0,seattle,wa,47.611435,-122.330456

In [32]:
df_new = df_new[df_new['rental_type']=='Monthly']
df_new.head()

,Parking,Laundry,Dishwasher,Stainless_Appliances,Cable,Internet,Outdoor_Spaces,AC,Pool,Fitness_Facilities,rental_type,Price,Unit_Type,Bedrooms,city_clean,state_clean,latitude,longitude
0,False,False,False,False,False,False,False,False,False,False,Monthly,940.0,studio,0,washington,dc,38.912217,-77.017691
1,False,False,False,False,False,False,False,False,False,False,Monthly,425.0,studio,0,evansville,in,37.974600,-87.567400
2,False,False,False,False,False,False,False,False,False,False,Monthly,445.0,1 bedroom,1,evansville,in,37.974600,-87.567400
3,False,False,False,False,False,False,NaN,False,False,False,Monthly,1390.0,studio,0,arlington,va,38.887103,-77.093197
4,False,False,False,False,False,False,False,False,False,False,Monthly,925.0,studio,0,seattle,wa,47.611435,-122.330456

In [37]:
df_new['city_clean'] = df_new['city_clean'].str.title()
df_new['state_clean'] = df_new['state_clean'].str.upper()
df_new.head()

,Parking,Laundry,Dishwasher,Stainless_Appliances,Cable,Internet,Outdoor_Spaces,AC,Pool,Fitness_Facilities,rental_type,Price,Unit_Type,Bedrooms,city_clean,state_clean,latitude,longitude
0,False,False,False,False,False,False,False,False,False,False,Monthly,940.0,studio,0,Washington,DC,38.912217,-77.017691
1,False,False,False,False,False,False,False,False,False,False,Monthly,425.0,studio,0,Evansville,IN,37.974600,-87.567400
2,False,False,False,False,False,False,False,False,False,False,Monthly,445.0,1 bedroom,1,Evansville,IN,37.974600,-87.567400
3,False,False,False,False,False,False,NaN,False,False,False,Monthly,1390.0,studio,0,Arlington,VA,38.887103,-77.093197
4,False,False,False,False,False,False,False,False,False,False,Monthly,925.0,studio,0,Seattle,WA,47.611435,-122.330456

In [38]:
df_new.to_csv('housing.csv', index=False)