In [1]:
import pandas as pd
import glob

# Find all the chunk CSV files in your output directory
all_files = ['/kaggle/input/data-chunks/structured_data_chunk_0.csv','/kaggle/input/data-chunks/structured_data_chunk_1.csv', '/kaggle/input/data-chunks/structured_data_chunk_2.csv', '/kaggle/input/data-chunks/structured_data_chunk_3.csv', '/kaggle/input/data-chunks/structured_data_chunk_4.csv', '/kaggle/input/data-chunks/structured_data_chunk_5.csv', '/kaggle/input/data-chunks/structured_data_chunk_6.csv']


# Load each CSV into a DataFrame and store it in a list
li = []
for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)

# Concatenate all DataFrames into one
final_df = pd.concat(li, axis=0, ignore_index=True)

# Save the final, complete dataset
final_df.to_csv('/kaggle/working/final_comprehensive_dataset.csv', index=False)

print(f"Successfully combined {len(all_files)} chunks into one file with {len(final_df)} rows.")
display(final_df.head())

Successfully combined 7 chunks into one file with 12376 rows.

,Parking,Flooring,Laundry,Dishwasher,Stainless_Appliances,Cable,Internet,Outdoor_Spaces,AC,Pool,Fitness_Facilities,State,City,rental_type,Price,Unit_Type,Bedrooms,Fireplace
0,not,other,not,not,not,not,not,No Outdoor Space,not,not,not,DC,Washington,Monthly,940.0,studio,0,NaN
1,not,other,not,not,not,not,not,No Outdoor Space,not,not,not,IN,Evansville,Monthly,425.0,studio,0,NaN
2,not,other,not,not,not,not,not,No Outdoor Space,not,not,not,IN,Evansville,Monthly,445.0,1 bedroom,1,NaN
3,not,other,not,not,not,not,not,combined,not,not,not,VA,Arlington,Monthly,1390.0,studio,0,NaN
4,not,other,not,not,not,not,not,No Outdoor Space,not,not,not,WA,Seattle,Monthly,925.0,studio,0,NaN

In [2]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12376 entries, 0 to 12375
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Parking               12376 non-null  object
 1   Flooring              12376 non-null  object
 2   Laundry               12376 non-null  object
 3   Dishwasher            12376 non-null  object
 4   Stainless_Appliances  12376 non-null  object
 5   Cable                 12376 non-null  object
 6   Internet              12376 non-null  object
 7   Outdoor_Spaces        12376 non-null  object
 8   AC                    12376 non-null  object
 9   Pool                  12359 non-null  object
 10  Fitness_Facilities    12359 non-null  object
 11  State                 12376 non-null  object
 12  City                  12373 non-null  object
 13  rental_type           12376 non-null  object
 14  Price                 12376 non-null  float64
 15  Unit_Type             12376 non-null  object
 16  Bedrooms              12376 non-null  int64
 17  Fireplace             3 non-null      object
dtypes: float64(1), int64(1), object(16)
memory usage: 1.7+ MB

In [3]:
final_df = final_df.drop('Fireplace', axis=1)

In [4]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12376 entries, 0 to 12375
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Parking               12376 non-null  object
 1   Flooring              12376 non-null  object
 2   Laundry               12376 non-null  object
 3   Dishwasher            12376 non-null  object
 4   Stainless_Appliances  12376 non-null  object
 5   Cable                 12376 non-null  object
 6   Internet              12376 non-null  object
 7   Outdoor_Spaces        12376 non-null  object
 8   AC                    12376 non-null  object
 9   Pool                  12359 non-null  object
 10  Fitness_Facilities    12359 non-null  object
 11  State                 12376 non-null  object
 12  City                  12373 non-null  object
 13  rental_type           12376 non-null  object
 14  Price                 12376 non-null  float64
 15  Unit_Type             12376 non-null  object
 16  Bedrooms              12376 non-null  int64
dtypes: float64(1), int64(1), object(15)
memory usage: 1.6+ MB

In [5]:
final_df['Parking'].value_counts()

Parking
not         9549
provided    2827
Name: count, dtype: int64

In [6]:
recode = {"not" : "other"}
final_df['Flooring'] = final_df['Flooring'].replace(recode)
final_df['Flooring'].value_counts()

Flooring
other     9579
carpet    2243
wood       543
tile        11
Name: count, dtype: int64

In [10]:
final_df['Laundry'].value_counts()

Laundry
not         7169
provided    5207
Name: count, dtype: int64

In [11]:
final_df['Dishwasher'].value_counts()

Dishwasher
not         7878
provided    4498
Name: count, dtype: int64

In [12]:


final_df['Stainless_Appliances'].value_counts()

Stainless_Appliances
not         12301
provided       75
Name: count, dtype: int64

In [7]:
recode = {"provided" : "included"}
final_df['Cable'] = final_df['Cable'].replace(recode)
final_df['Cable'].value_counts()

Cable
not         12138
included      238
Name: count, dtype: int64

In [8]:
recode = {"provided" : "included"}
final_df['Internet'] = final_df['Internet'].replace(recode)
final_df['Internet'].value_counts()

Internet
not         11882
included      494
Name: count, dtype: int64

In [9]:
recode = {"Pool" : "No Outdoor Space", "other" : "No Outdoor Space", "Porch" : "No Outdoor Space", "not" : "No Outdoor Space", "Den" : "No Outdoor Space", "Fitness facilities" : "No Outdoor Space", "Yard" : "No Outdoor Space", "Picnic areas with grills" : "No Outdoor Space", "combined" : "Combined", "Balcony, Patio, Deck" : "Combined", "Balcony, Patio" : "Combined" , "Balcony, Patio, Deck, Combined" : "Combined"}
final_df['Outdoor_Spaces'] = final_df['Outdoor_Spaces'].replace(recode)
final_df['Outdoor_Spaces'].value_counts()

Outdoor_Spaces
No Outdoor Space    7437
Combined            3132
Balcony             1785
Patio                 13
Deck                   9
Name: count, dtype: int64

In [10]:
recode = {"included" : "provided" }
final_df['AC'] = final_df['AC'].replace(recode)
final_df['AC'].value_counts()

AC
not         9381
provided    2995
Name: count, dtype: int64

In [17]:
final_df['Pool'].value_counts()

Pool
not         10998
provided     1361
Name: count, dtype: int64

In [11]:
recode = {"provided" : "available" }
final_df['Fitness_Facilities'] = final_df['Fitness_Facilities'].replace(recode)
final_df['Fitness_Facilities'].value_counts()

Fitness_Facilities
not          8889
available    3470
Name: count, dtype: int64

In [19]:
final_df['State'].value_counts()

State
TX               2920
CA               1039
WI                508
IL                497
WA                475
FL                472
MN                456
IN                440
MO                405
OR                292
MI                286
IA                285
CO                282
GA                280
NC                248
VA                226
OH                208
AZ                203
PA                198
NE                189
ND                186
KS                183
TN                165
MA                160
OK                148
MD                139
UT                137
NJ                117
SD                111
NY                106
AR                 92
DC                 91
LA                 90
AL                 85
SC                 83
AK                 82
KY                 78
NV                 73
CT                 66
not                41
ID                 38
Tx                 32
RI                 30
unknown            27
NM                 23
NH                 18
MS                 17
HI                 13
DE                  9
MT                  7
N                   7
VT                  6
North Phoenix       3
WV                  2
WY                  1
ME                  1
Name: count, dtype: int64

In [20]:
final_df['City'].value_counts()

City
Austin           1356
San Antonio       435
Chicago           253
Madison           170
Portland          167
                 ...
Oakdale             1
Mill Creek          1
Lemon Grove         1
Panorama City       1
Bella Vista         1
Name: count, Length: 1353, dtype: int64

In [21]:
final_df['rental_type'].value_counts()

rental_type
Monthly    12244
other        132
Name: count, dtype: int64

In [12]:
recode = {"1 beds" : "1 bedroom", "2 beds" : "2 bedroom"  }
final_df['Unit_Type'] = final_df['Unit_Type'].replace(recode)
final_df['Unit_Type'].value_counts()

Unit_Type
2 bedroom    4208
1 bedroom    3819
3 bedroom    2175
studio       1515
4 bedroom     560
5 bedroom      99
Name: count, dtype: int64

In [13]:
final_df['Bedrooms'].value_counts()

Bedrooms
2    4208
1    3819
3    2175
0    1515
4     560
5      99
Name: count, dtype: int64

In [14]:
# Save the final, complete dataset
final_df.to_csv('/kaggle/working/final_comprehensive_dataset.csv', index=False)

print(f"Successfully combined {len(all_files)} chunks into one file with {len(final_df)} rows.")
display(final_df.head())

Successfully combined 7 chunks into one file with 12376 rows.

,Parking,Flooring,Laundry,Dishwasher,Stainless_Appliances,Cable,Internet,Outdoor_Spaces,AC,Pool,Fitness_Facilities,State,City,rental_type,Price,Unit_Type,Bedrooms
0,not,other,not,not,not,not,not,No Outdoor Space,not,not,not,DC,Washington,Monthly,940.0,studio,0
1,not,other,not,not,not,not,not,No Outdoor Space,not,not,not,IN,Evansville,Monthly,425.0,studio,0
2,not,other,not,not,not,not,not,No Outdoor Space,not,not,not,IN,Evansville,Monthly,445.0,1 bedroom,1
3,not,other,not,not,not,not,not,Combined,not,not,not,VA,Arlington,Monthly,1390.0,studio,0
4,not,other,not,not,not,not,not,No Outdoor Space,not,not,not,WA,Seattle,Monthly,925.0,studio,0